
baseURL = 'https://www.rafasacaan.com/'
languageCode = 'en-us'
title = 'rafa sacaan'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Un blog... un cuaderno, en realidad."

# Appearance settings
theme = 'auto'
colorPalette = 'base16-mocha'
hideHeader = false

# Intro on main page, content is markdown
#homeIntroTitle = 'Hola!'
homeIntroContent = """
Hola, soy rafa de Chile🇨🇱. \n
Me obsesiona la idea de que la tecnología pueda ayudarnos a **encontrarnos a nosotros mismos**.
Algo así como usar la tecnología para des-tecnologizarnos y encontrar nuestro yo más auténtico.
Me gusta crear apps para investigar esto.\n

Soy fanático de la música, sobre todo si está grabada en alguna maquinita digital o análoga antigua. También me gustan mucho la literatura y las fotos.
Me encantan los objetos y las cosas, especialmente las que nos evocan algo.\n
"""

# Collection to display on home
# homeCollectionTitle = 'apps'
# homeCollection = 'apps'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rafaelsacaanamunategui/"

[[params.social]]
name = "github"
url = "https://github.com/rafasacaan"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "apps"
url = "/apps"


[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"