
baseURL = 'https://www.rafasacaan.com/'
languageCode = 'en-us'
title = 'rafa sacaan'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Un blog... un cuaderno, en realidad."

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
#homeIntroTitle = 'Hola!'
homeIntroContent = """
Soy Rafa de 🇨🇱, ingeniero eléctrico con base en la matemática y estadística, y trabajo como data scientist.\n 
Estoy interesado en eliminar el ruido que existe entre los problemas del mundo real y las herramientas que usamos. \n
Me gustan los problemas complejos, pero me gustan mucho más las historias y las soluciones simples.\n
Estoy interesado en temas como la estadística y la economía, la simulación y la optimización... y tal vez algún algoritmo de ML/AI si es que le quitamos el hype.\n
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rafaelsacaanamunategui/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/rafasacaan"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

